spring.application.name=event-sourcing-cqrs
server.port=8080
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/eventsourcing}
spring.datasource.username=${DB_USERNAME:eventsourcing}
spring.datasource.password=${DB_PASSWORD:changeme}
spring.jpa.hibernate.ddl-auto=update
