spring.application.name=event-sourcing-cqrs
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/eventsourcing
spring.datasource.username=eventsourcing
spring.datasource.password=eventsourcing
spring.jpa.hibernate.ddl-auto=update
